# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 17:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('last_date_of_registration', models.DateField()),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('late_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_age', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='Only digits allowed.', regex='^[0-9]*$')])),
                ('max_age', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='Only digits allowed.', regex='^[0-9]*$')])),
                ('remarks', models.TextField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Address')),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Only digits allowed.', regex='^[0-9]*$')])),
                ('accommodation', models.BooleanField()),
                ('payment_status', models.BooleanField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cashier', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('pariticipant', 'Participant'), ('helper', 'Helper'), ('coordinator', 'Coordinator')], max_length=12)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('event_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_center', to='base.Center')),
                ('home_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_center', to='base.Center')),
                ('pariticipant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Participant')),
            ],
        ),
    ]
