# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 19:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(help_text='Event End Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fees',
            field=models.DecimalField(decimal_places=2, help_text='Event Fees', max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_date_of_registration',
            field=models.DateField(help_text='Last Date of Registration'),
        ),
        migrations.AlterField(
            model_name='event',
            name='late_fees',
            field=models.DecimalField(decimal_places=2, help_text='Late Registration Fees', max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_age',
            field=models.CharField(help_text='Age Group Upper limit', max_length=2, validators=[django.core.validators.RegexValidator(message='Only digits allowed.', regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='min_age',
            field=models.CharField(help_text='Age Group Lower limit', max_length=2, validators=[django.core.validators.RegexValidator(message='Only digits allowed.', regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='Event Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='remarks',
            field=models.TextField(help_text='Any remarks'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(help_text='Event Start Date'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='accommodation',
            field=models.BooleanField(help_text='Is accommodation required?'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, help_text='Amount paid', max_digits=10),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='cashier',
            field=models.CharField(help_text='Cashier', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='event_center',
            field=models.ForeignKey(blank=True, help_text='Event Center', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_center', to='base.Center'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='home_center',
            field=models.ForeignKey(help_text='Home Center', on_delete=django.db.models.deletion.CASCADE, related_name='home_center', to='base.Center'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='payment_status',
            field=models.BooleanField(help_text='Has paid?'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='registration_no',
            field=models.CharField(help_text='Registration Number', max_length=20, validators=[django.core.validators.RegexValidator(message='Only digits allowed.', regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='role',
            field=models.CharField(choices=[('pariticipant', 'Participant'), ('helper', 'Helper'), ('coordinator', 'Coordinator')], help_text='Role', max_length=12),
        ),
    ]
