# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipant',
            name='id',
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='big_buddy',
            field=models.CharField(blank=True, help_text='Big Buddy', max_length=50),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='goal_achievement',
            field=models.CharField(blank=True, help_text='Goal Achievement', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='cashier',
            field=models.CharField(blank=True, help_text='Cashier', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='registration_no',
            field=models.BigAutoField(help_text='Registration Number', primary_key=True, serialize=False),
        ),
    ]
