# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 07:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170711_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accommodation_provided',
            field=models.BooleanField(default=False, help_text='Is Accommodation Provided?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='rules',
            field=models.TextField(blank=True, help_text='Any Rules'),
        ),
        migrations.AlterField(
            model_name='event',
            name='remarks',
            field=models.TextField(blank=True, help_text='Any Remarks'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='accommodation',
            field=models.BooleanField(help_text='Is Accommodation Required?'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, help_text='Amount Paid', max_digits=10),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='registration_no',
            field=models.CharField(help_text='Registration Number', max_length=20, validators=[django.core.validators.RegexValidator(message='Only digits allowed.', regex='^[0-9 a-z A-Z]*$')]),
        ),
    ]
