# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_center'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventparticipant',
            old_name='pariticipant',
            new_name='participant',
        ),
    ]
