# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-10 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20190709_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(default=1, editable=False, help_text='Event Category', on_delete=django.db.models.deletion.CASCADE, to='events.EventCategory'),
        ),
    ]
