# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-10-19 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20190710_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(default='', help_text='Event Category', on_delete=django.db.models.deletion.CASCADE, to='events.EventCategory'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='category',
            field=models.CharField(default='', help_text='Event Category', max_length=50),
        ),
    ]
