# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-10-19 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20191019_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_arrival_reg',
            field=models.BooleanField(default=False, help_text='Start arrival Registration'),
        ),
    ]
