# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-11 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_event_start_arrival_reg'),
        ('events', '0016_auto_20191019_1005'),
    ]

    operations = [
    ]
