# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-11 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20190710_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_global_poc',
            field=models.BooleanField(default=False, help_text='Is global PoC?'),
        ),
        migrations.AddField(
            model_name='event',
            name='poc_name',
            field=models.CharField(blank=True, help_text='Name of point of contact', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='poc_number',
            field=models.CharField(blank=True, help_text='Contact number of POC', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.PositiveIntegerField(choices=[(2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2020, help_text='year'),
        ),
    ]
