# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20170719_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(help_text='Country', max_length=30),
        ),
    ]
