# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-29 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20170926_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='participant_code',
            field=models.CharField(blank=True, help_text='Participant Code', max_length=100),
        ),
    ]
