# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-01 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_participant_participant_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant_code',
            field=models.CharField(blank=True, default='', help_text='Participant Code', max_length=100),
        ),
    ]
